// AUTO-GENERATED — do not edit. Source: data/i18n/strings.json
// ignore_for_file: lines_longer_than_80_chars

// ignore: avoid_classes_with_only_static_members
class LocalizationData {
  static const Map<String, String> strings = {
    'configMenuTitle': 'Settings',
    'loading': 'Loading...',
    'snackCopied': 'Copied to clipboard',
    'noOutput': '(no output)',
    'errorResult': '[Error] {e}',
    'logErrorTag': '[Error]',
    'languageChinese': 'Chinese',
    'languageJapanese': 'Japanese',
    'languageEnglish': 'English',
    'menuProject': 'Projects',
    'menuWebshell': 'Webshell',
    'menuExp': 'Exploits',
    'menuPayload': 'Payloads',
    'menuTerminal': 'Terminal',
    'menuFrp': 'FRP Client',
    'menuSuo5': 'suo5 Proxy',
    'sidebarCollapse': 'Collapse',
    'sidebarExpandTooltip': 'Expand menu',
    'workspaceWelcomeTitle': '> Welcome to Matrix',
    'workspaceWelcomeSubtitle': 'Current page: {pageTitle} · Let\'s get started',
    'workspaceQuickActions': 'Quick actions',
    'quickActionNew': 'New',
    'workspaceRecentActivities': 'Recent activity',
    'recentFileTitle': 'Project file {index}',
    'recentHoursAgo': '{hours} hours ago',
    'actionNewProject': 'New project',
    'actionAddWebshell': 'Add Webshell',
    'actionGoCreateProject': 'Create project',
    'actionRefresh': 'Refresh',
    'actionListenConfig': 'Listener config',
    'actionCopy': 'Copy',
    'actionCopyBase64': 'Copy as Base64',
    'actionDownload': 'Download',
    'quickActionUpload': 'Upload',
    'quickActionOpen': 'Open',
    'tabFileManager': 'File manager',
    'tabTerminal': 'Terminal',
    'tabSysInfo': 'System info',
    'sectionPrivEsc': 'Privilege check',
    'btnCancel': 'Cancel',
    'btnConfirm': 'OK',
    'btnSave': 'Save',
    'btnDelete': 'Delete',
    'btnCreate': 'Create',
    'btnClose': 'Close',
    'btnAdd': 'Add',
    'btnRetry': 'Retry',
    'btnClear': 'Clear',
    'btnExecute': 'Run',
    'btnAutoDetect': 'Auto detect',
    'btnSwitchProject': 'Switch project',
    'btnStartListen': 'Start listen',
    'btnStopListen': 'Stop listen',
    'btnPortOccupied': 'Port in use',
    'btnCheckAll': 'Check all',
    'tooltipEdit': 'Edit',
    'tooltipDelete': 'Delete',
    'tooltipBack': 'Back',
    'tooltipView': 'View',
    'tooltipCopyContent': 'Copy content',
    'tooltipClearTerminal': 'Clear terminal',
    'tooltipFullTerminal': 'Full terminal (reverse shell)',
    'tooltipParentDir': 'Parent directory',
    'tooltipUploadFile': 'Upload file',
    'tooltipDownload': 'Download',
    'tooltipClose': 'Close',
    'selectDownloadDir': 'Select download folder',
    'snackWriteNotSupported': 'Current connector does not support file write',
    'tooltipSwitchToSeparate': 'Switch to split mode (bottom input bar)',
    'tooltipSwitchToIntegrated': 'Switch to integrated mode (terminal-like)',
    'payloadCount': '{n} files',
    'titleDeletePayload': 'Delete payload',
    'confirmDeletePayload': 'Delete "{name}"?\nThis action cannot be undone.',
    'payloadNoneFound': 'No payloads found',
    'payloadImportHint': 'Import a file to get started',
    'payloadBuiltinTooltip': 'Built-in default, cannot delete',
    'payloadBuiltin': 'Built-in',
    'binaryPreviewDisabled': 'Binary payload detected.\nPreview disabled.',
    'snackImported': 'Imported {name}',
    'snackImportFailed': 'Import failed: {e}',
    'snackSavedTo': 'Saved to {path}',
    'snackSaveFailed': 'Save failed: {e}',
    'snackBinaryCopyUnsupported': 'Binary payload cannot be copied as text',
    'snackCopiedBase64': 'Copied as Base64',
    'fieldProjectName': 'Project name',
    'fieldDomainOrId': 'Target URL *',
    'hintDomainOrId': 'e.g. https://target.example or http://192.168.1.1:8080',
    'fieldDescription': 'Description (optional)',
    'titleEditProject': 'Edit project #{id}',
    'webModeWarning': 'Web mode: data is stored in memory only and will be lost on refresh. Use the desktop app for persistent storage.',
    'projectEmptyHint': 'No projects yet. Click "{newProjectLabel}" to get started',
    'projectCreatedUpdated': 'Created {created} · Updated {updated}',
    'menuEnterWebshell': 'Open Webshell',
    'menuEnterExp': 'Open Exploits',
    'dialogChooseProjectEntryTitle': 'Choose where to open',
    'confirmDeleteProject': 'Delete project "{name}"? This will also delete its Webshell and collected data. This action cannot be undone.',
    'noProjects': 'No projects',
    'noProjectsHint': 'Please create a project before using this feature',
    'selectProject': 'Select a project',
    'titleSelectProject': 'Select project',
    'terminalTitle': 'Full terminal · Reverse shell sessions',
    'noActiveSessions': 'No active reverse shell sessions',
    'activeSessionCount': 'Active sessions: {n}',
    'listeningOn': 'Listening: {addr}:{port}',
    'portOccupiedOn': 'Port in use: {addr}:{port} (may already be listening)',
    'notListening': 'Not listening (config: {host}:{port})',
    'fieldLhost': 'Listen IP (LHOST)',
    'fieldLport': 'Listen port (LPORT)',
    'snackPortOccupied': 'Port is in use. Release it before starting to listen',
    'snackListenStarted': 'Listening on :{lport} (LHOST={lhost})',
    'snackListenFailed': 'Failed to start listener: {e}',
    'noSessionsHint': '> No sessions. Click "Full terminal" in the Webshell terminal to start a reverse shell.',
    'snackSessionDisconnected': 'Session disconnected, cannot open terminal',
    'sessionDisconnected': 'Disconnected',
    'pingFailHint': 'Check: ① Connector type matches the target script; ② URL is accessible in a browser.',
    'connectionFailed': 'Connection failed, command execution may be unreliable',
    'statusChecking': 'Checking',
    'statusConnected': 'Connected',
    'statusReconnect': 'Reconnect',
    'titleSelectTerminalMode': 'Select terminal mode',
    'terminalModeScript': 'Built-in reverse · script mode',
    'terminalModeScriptDesc': 'Uses script to allocate a pseudo-terminal. Recommended for Unix-like targets',
    'terminalModeBash': 'Built-in reverse · bash mode',
    'terminalModeBashDesc': 'No script dependency. Uses bash -i or /bin/sh -i only',
    'snackReverseShellSent': 'Reverse shell command sent, waiting for connection ...',
    'snackStartFailed': 'Failed to start: {e}',
    'terminalEmptyHint': '> Type a command to get started',
    'terminalKeyHint': 'Use ↑↓ to navigate history, type clear to reset',
    'modeIntegrated': 'Integrated',
    'modeSeparate': 'Split',
    'tabCompletionTitle': 'Tab candidates ({total})',
    'noCompletions': 'No candidates',
    'executing': 'Running...',
    'fieldWebshellUrl': 'Webshell URL *',
    'hintWebshellUrl': 'http://example.com/shell.php',
    'fieldWebshellName': 'Alias (optional)',
    'hintWebshellName': 'e.g. Admin panel shell',
    'labelRequestMethod': 'Request method:',
    'snackFillUrlAndPassword': 'Please enter the URL and password first',
    'titleEditWebshell': 'Edit Webshell',
    'confirmDeleteWebshell': 'Delete "{name}"? This action cannot be undone.',
    'webshellManagementTitle': 'Webshell · {projectName}',
    'expManagementScopedTitle': 'Exploits · {projectName}',
    'webshellCount': '{n} total',
    'webshellEmptyHint': 'No Webshell yet. Click "{addLabel}" to get started',
    'webshellPasswordLabel': 'Password',
    'connectorMethodFixed': 'Fixed by connector',
    'fieldConnectorType': 'Connector type',
    'unknownConnector': 'Unknown: {value}',
    'fieldPasswordKey': 'Password / key *',
    'fieldParamName': 'Parameter name *',
    'hintPasswordKey': 'Default mAtrix_911, or the 16-char hex of k in the payload',
    'helperPasswordKey': 'Connection password (first 16 chars of MD5 as key); or enter the hex value of String k="xxx" from the payload directly',
    'helperParamName': 'HTTP parameter name for receiving commands in the payload (e.g. \$_POST["{param}"])',
    'hintParamName': 'Parameter name, default: {param}',
    'detectSuccess': 'Detection complete. Auto-selected the first responsive connector type',
    'detectFailed': 'No responsive connector found. Check the URL and password',
    'snackWriteUnsupported': 'Current connector does not support file writing',
    'allFiles': 'All files',
    'snackNoPayloads': 'No payloads available to upload',
    'snackPayloadDecodeFailed': 'Payload decode failed: {name}',
    'dirEmptyOrDenied': 'Directory is empty or access denied',
    'dirEmpty': 'Directory is empty',
    'colName': 'Name',
    'colSize': 'Size',
    'colPermissions': 'Perms',
    'colModified': 'Modified',
    'titleConfirmDelete': 'Confirm delete',
    'confirmDeleteFile': 'Delete "{name}"? This action cannot be undone.',
    'snackDeleted': 'Deleted {name}',
    'snackDeleteFailed': 'Delete failed',
    'snackUploadCancelled': 'Upload cancelled',
    'snackUploadFailed': 'Upload failed: {e}',
    'snackUploaded': 'Uploaded {fileName}',
    'snackUploadFail': 'Upload failed',
    'snackDownloadedTo': 'Saved to {path}',
    'snackDownloadFailed': 'Download failed: {e}',
    'titleSelectPayload': 'Select payload to upload',
    'tooltipPayloadUploadToWebshellTmp': 'Upload to Webshell /tmp',
    'titleSelectWebshellForPayload': 'Select Webshell (upload to /tmp)',
    'snackNoWebshellsAnyProject': 'No Webshell found. Add one under Webshell first',
    'snackPayloadUploadedToRemote': 'Uploaded to {remotePath}',
    'dialogUploadSuccessTitle': 'Upload successful',
    'dialogUploadFailureTitle': 'Upload failed',
    'uploading': 'Uploading',
    'downloading': 'Downloading',
    'uploadingProgress': 'Uploading...',
    'downloadingProgress': 'Receiving data, please wait...',
    'snackSaveSuccess': 'Saved successfully',
    'snackSaveFailure': 'Save failed',
    'serverInfo': 'Server information',
    'sysInfoFailed': 'Failed to retrieve system info',
    'sysInfoFailedHint': 'Check whether the Webshell can execute remote code/commands normally',
    'disabledFunctions': 'Disabled functions ({n})',
    'loadedExtensions': 'Loaded extensions ({n})',
    'sysInfoFieldOs': 'OS',
    'sysInfoFieldPhpVersion': 'PHP version',
    'sysInfoFieldRunUser': 'Runtime user',
    'sysInfoFieldServerIp': 'Server IP',
    'sysInfoFieldServerSoftware': 'Server software',
    'sysInfoFieldDocRoot': 'Document root',
    'sysInfoFieldCurrentDir': 'Current directory',
    'sysInfoFieldMemoryLimit': 'Memory limit',
    'sysInfoFieldMaxExecutionTime': 'Max execution time',
    'sysInfoFieldSafeMode': 'Safe Mode',
    'sysInfoFieldHost': 'Hostname',
    'sysInfoFieldUserId': 'User ID',
    'sysInfoFieldKernelVersion': 'Kernel version',
    'sysInfoFieldDotnetClr': '.NET CLR version',
    'privEscTitle': 'Privilege escalation checks',
    'checkingAll': 'Checking…',
    'privEscSuggestions': 'Privilege escalation suggestions (based on results)',
    'privEscGroupCurrentPriv': 'Current privileges',
    'privEscGroupSysInfo': 'System info',
    'privEscGroupEscVectors': 'Escalation vectors',
    'privEscGroupSensitiveInfo': 'Sensitive information',
    'privEscItemUserGroup': 'User & group',
    'privEscItemUserGroupDesc': 'Current user UID/GID and groups',
    'privEscItemSudo': 'Sudo privileges',
    'privEscItemSudoDesc': 'Commands executable via sudo without password',
    'privEscItemEnv': 'Environment variables',
    'privEscItemEnvDesc': 'Environment variables may contain credentials',
    'privEscItemKernel': 'Kernel version',
    'privEscItemKernelDesc': 'Check kernel version to match local privilege escalation exploits',
    'privEscItemDistro': 'Distribution',
    'privEscItemDistroDesc': 'Linux distribution and version',
    'privEscItemLoggedUsers': 'Logged-in users',
    'privEscItemLoggedUsersDesc': 'Current active sessions',
    'privEscItemRootProcs': 'Processes running as root',
    'privEscItemRootProcsDesc': 'Service processes running as root',
    'privEscItemSuid': 'SUID files',
    'privEscItemSuidDesc': 'Executables with SUID bit set (may be used for escalation)',
    'privEscItemSgid': 'SGID files',
    'privEscItemSgidDesc': 'Executables with SGID bit set',
    'privEscItemCap': 'Capabilities',
    'privEscItemCapDesc': 'Files with Linux capabilities',
    'privEscItemCron': 'Cron jobs',
    'privEscItemCronDesc': 'Scheduled task configuration and scripts',
    'privEscItemCronWritable': 'Writable cron scripts',
    'privEscItemCronWritableDesc': 'Writable by current user/group based on permission bits (read-only check, no side effects)',
    'privEscItemWritableDirs': 'Writable directories',
    'privEscItemWritableDirsDesc': 'Directories writable by the current user',
    'privEscItemPathHijack': 'PATH hijacking',
    'privEscItemPathHijackDesc': 'Check for writable directories in PATH',
    'privEscItemLoginableAccounts': 'Loginable accounts',
    'privEscItemLoginableAccountsDesc': 'User accounts that can log in normally',
    'privEscItemShadow': 'Shadow file',
    'privEscItemShadowDesc': 'Attempt to read password hashes (requires root)',
    'privEscItemHistory': 'Command history',
    'privEscItemHistoryDesc': 'Command history may contain plaintext credentials',
    'privEscItemSshKeys': 'SSH keys',
    'privEscItemSshKeysDesc': 'Whether private key files are readable',
    'privEscItemConfigPasswords': 'Config file passwords',
    'privEscItemConfigPasswordsDesc': 'Plaintext passwords in web/system config files',
    'privEscSudoAllTitle': 'Sudo passwordless escalation',
    'privEscSudoAllReason': 'Detected sudo can run ALL without password. Direct escalation:',
    'privEscSudoLimitedTitle': 'Sudo limited command escalation',
    'privEscSudoLimitedReason': 'Detected passwordless sudo: {paths}',
    'privEscSuidTitle': 'SUID escalation',
    'privEscSuidReason': 'Found exploitable SUID files. Execute in terminal (requires writable directory):',
    'privEscKernelTitle': 'Kernel escalation (find exploit locally)',
    'privEscKernelReason': 'Kernel {ver} ({arch}). Search for matching CVE locally',
    'privEscShadowTitle': 'Password hash cracking (crack locally)',
    'privEscShadowReason': 'Obtained shadow. Crack locally ({hashMode}). Success rate depends on password strength',
    'privEscCronTitle': 'Cron hijacking (write access confirmed)',
    'privEscCronReason': 'Auto-detected writable cron files: {paths}',
    'privEscCapTitle': 'Capabilities escalation',
    'privEscCapReason': 'Found cap_setuid. Execute the path above directly:',
    'expWaiting': '> Awaiting action',
    'statusRunning': 'Running',
    'statusIdle': 'Idle',
    'expManagementTitle': 'EXP Management',
    'expManagementHint': 'Manage all exploit modules here. Tap an entry to open its exploit interface',
    'expVersionRequirement': 'Version requirement: {ver}',
    'sectionTargetConfig': 'Target config',
    'fieldTargetUrl': 'Target URL',
    'fieldTimeout': 'Timeout (s)',
    'fieldCommand': 'Command',
    'btnDetect': 'Detect',
    'btnDetectVuln': 'Detect vuln',
    'btnDetectAll': 'Detect all',
    'btnExecCmd': 'Execute command',
    'btnSubmitCmd': 'Submit command',
    'sectionCmdExec': 'Command execution',
    'sectionGetShell': 'GetShell (reverse shell)',
    'fieldAttackerIp': 'Attacker IP',
    'fieldAttackerPort': 'Attacker port',
    'btnStartReverseShell': 'Start reverse shell',
    'fieldShellPassword': 'Shell password',
    'btnWriteWebShell': 'Write WebShell',
    'sectionVulnSelect': 'Vuln selection',
    'titleWebshellManager': 'Webshell',
    'expLogEnterTargetUrl': '[!] Please enter the target URL',
    'expLogException': '[!] Error: {e}',
    'expLogInvalidLhostLport': '[!] Invalid LHOST/LPORT',
    'expLogNoVulnGeneric': '[-] No vulnerability detected',
    'expLogReverseSentWaiting': '[+] Reverse shell payload sent, waiting for connection...',
    'expLogSendFailed': '[-] Send failed',
    'expLogStartFailed': '[!] Failed to start: {e}',
    'expLogStartFullTerminalListen': '[*] Starting full-terminal listener: {lhost}:{lport} ({mode})',
    'terminalConnectionClosed': 'Connection closed',
    'frpLogCopiedSnack': 'Log copied to clipboard',
    'frpDupDisplayName': '{base} copy',
    'frpDupDisplayNameIndexed': '{base} copy ({i})',
    'frpDupProxyFirst': '{proxyName}_copy',
    'frpDupProxyIndexed': '{proxyName}_copy{i}',
    'frpAuthMd5Label': 'MD5 (official default)',
    'frpAuthHmacSha1Label': 'HMAC-SHA1',
    'frpAuthHmacSha256Label': 'HMAC-SHA256',
    'frpAuthRawTokenLabel': 'Raw Token',
    'sectionVulnType': 'Vulnerability type',
    'nacosStep2': 'Step 2 — Derby SQL RCE',
    'sectionSshModuleCmdInject': 'SSH module command injection',
    'btnGetShell': 'GetShell',
    'connectorUiLabelDetail': '{stack} · {short}',
    'detectPingOk': 'Responded',
    'detectPingNo': 'No response',
    'detectPingTimeout': 'Timeout',
    'detectPingConnectFailed': 'Connection failed',
    'terminalFullTitle': 'Full terminal · {label}',
    'btnDisconnect': 'Disconnect',
    'actionPaste': 'Paste',
    'frpTunnelTitle': 'FRP Client',
    'frpStatusRunning': 'Tunnel running · Remote traffic is being forwarded locally',
    'frpStatusConnecting': 'Connecting...',
    'frpStatusError': 'Connection error. Check parameters or logs',
    'frpStatusIdle': 'Ready · Click "Start" in the list to connect the tunnel',
    'frpSavedConfigs': 'Saved profiles',
    'frpNoConfigs': 'No profiles yet. Click "New profile" below to add one.',
    'frpNewConfig': 'New profile',
    'frpRunLog': 'Run log',
    'frpNoLogs': '> No logs yet',
    'frpDuplicatedSnack': 'Duplicated "{name}"\nProxy {proxyName} · Remote port {port} (distinct from original, edit as needed)',
    'frpDuplicateFailed': 'Duplicate failed: {e}',
    'frpMissingServerOrProxy': 'This profile is missing a server address or proxy name. Edit and save first',
    'frpDeleteTitle': 'Delete profile',
    'frpConfirmDelete': 'Delete "{name}"? This action cannot be undone.',
    'frpDeletedSnack': 'Deleted "{name}"',
    'frpMappingLabel': 'Remote port {remotePort} → Local {localAddr}:{localPort}',
    'frpServerLabel': 'frp server {serverAddr}:{serverPort}',
    'btnStart': 'Start',
    'btnStop': 'Stop',
    'btnEdit': 'Edit',
    'btnDuplicate': 'Duplicate',
    'frpNewConfigTitle': 'New profile',
    'frpEditConfigTitle': 'Edit profile',
    'frpRunningNoEdit': 'Cannot edit while running',
    'frpAutoSave': 'Changes auto-save',
    'frpConfigName': 'Profile name',
    'frpConfigNameHint': 'e.g. Office network / Test server',
    'frpServerSection': 'Server config',
    'frpServerAddr': 'frp server address',
    'frpServerAddrHint': 'e.g. 1.2.3.4',
    'frpPort': 'Port',
    'frpProxySection': 'Proxy config',
    'frpProxyName': 'Proxy name',
    'frpRemotePort': 'Remote port',
    'frpLocalAddr': 'Local address',
    'frpLocalPort': 'Local port',
    'frpAdvanced': 'Advanced options',
    'frpVersionLabel': 'Client version (leave blank to omit)',
    'frpVersionHint': 'e.g. 0.51.3 / 0.61.1',
    'frpTcpMux': 'TCPMux (yamux multiplexing)',
    'frpAutoReconnect': 'Auto-reconnect on disconnect (retry after 5 s)',
    'frpAuthAlgorithm': 'Auth algorithm:',
    'frpToken': 'Token (optional)',
    'frpUnnamedConfig': 'Unnamed profile',
    'frpSaveFailed': 'Save failed: {e}',
    'frpActiveNotMatched': 'Tunnel active but does not match any saved profile (e.g. after navigation). Click "Stop" on the right',
    'frpStopConnection': 'Stop connection',
    'shiroPageTitle': 'Apache Shiro Deserialization Exploit',
    'shiroCardTitle': 'rememberMe Key bruteforce & exploit',
    'shiroCardSubtitle': 'Supports AES-CBC / AES-GCM. Bruteforce Key then load custom Payload',
    'shiroInnerTitle': 'Shiro deserialization',
    'shiroSectionKeyPayload': 'Key & Payload',
    'shiroSectionMemShell': 'In-memory Behinder shell injection',
    'shiroFieldMethod': 'Method',
    'shiroFieldMode': 'Mode',
    'shiroModeHint': 'Mode: custom Payload (only sends the Base64 below)',
    'shiroFieldCookieName': 'Cookie name',
    'shiroVerboseLog': 'Verbose log',
    'shiroCurrentKey': 'Current Key',
    'shiroKeyAutoFilled': 'Auto-filled after bruteforce',
    'shiroPayloadBase64': 'Payload Base64',
    'shiroPayloadHint': 'Paste Base64-encoded serialized Payload',
    'shiroCheckBtn': 'Detect Shiro',
    'shiroBruteforceBtn': 'Bruteforce Key',
    'shiroVerifyBtn': 'Verify Key',
    'shiroSendPayloadBtn': 'Send Payload',
    'shiroShellType': 'Shell type',
    'shiroShellPassword': 'Behinder password (16-char HEX)',
    'shiroShellPath': 'Shell path',
    'shiroMemShellDesc': 'Built-in CB1-InjectMemTool chain. No manual Payload required. After server deserialization, injects a Behinder memory shell via the user parameter.',
    'noProjectTitle': 'No projects',
    'hintCreateProjectForWebshell': 'Create a project first to save the Webshell',
    'fieldProjectNameHint': 'e.g. Target site',
    'fieldDomainOrIdHint': 'e.g. example.com',
    'btnSkip': 'Skip',
    'thinkphpTitle': 'ThinkPHP CVE-2018-20062/CVE-2019-9082/CNVD-2022-86535',
    'thinkphpSubtitle': 'Vuln detection, command execution, GetShell. 100% ThinkphpGUI replication',
    'thinkphpInnerTitle': 'ThinkPHP exploit',
    'thinkphpCurrentVuln': 'Current: {label}',
    'thinkphpSectionDetect': 'Vuln detection',
    'thinkphpSectionRce': 'RCE exploit',
    'thinkphpSingleVuln': 'Single CVE:',
    'thinkphpExploitVuln': 'Exploit CVE:',
    'thinkphpGetShellPassword': 'GetShell password',
    'thinkphpCheckAllRce': 'Detect all RCE',
    'zentaoTitle': 'Zentao CVE-2024-24216 · GetShell',
    'zentaoSubtitle': 'Exploit Zentao Repo config to write a Behinder WebShell. One-click GetShell',
    'zentaoRootPath': 'Zentao root path',
    'zentaoSectionExploit': 'Exploit actions',
    'zentaoDetectBtn': 'Probe / verify bypass',
    'vulhubDrupalTitle': 'Drupal CVE-2018-7600 (Drupalgeddon2) Form API RCE',
    'vulhubDrupalCardTitle': 'Drupal CVE-2018-7600',
    'vulhubDrupalCardSubtitle': 'Drupalgeddon2 — Form API #post_render callback PHP code execution',
    'vulhubFlaskSstiTitle': 'Flask / Jinja2 SSTI Server-Side Template Injection RCE',
    'vulhubFlaskSstiCardTitle': 'Flask / Jinja2 SSTI',
    'vulhubFlaskSstiCardSubtitle': 'Server-side Jinja2 template injection. Execute arbitrary Python code via URL parameter',
    'vulhubHttpdTitle': 'Apache HTTP Server CVE-2021-41773 Path Traversal + CGI RCE',
    'vulhubHttpdCardTitle': 'Apache HTTPd CVE-2021-41773',
    'vulhubHttpdCardSubtitle': 'Path normalization flaw — file read + CGI command execution (Apache 2.4.49)',
    'vulhubNacosTitle': 'Nacos CVE-2021-29441 User-Agent Auth Bypass',
    'vulhubNacosCardTitle': 'Nacos CVE-2021-29441',
    'vulhubNacosCardSubtitle': 'User-Agent: Nacos-Server bypasses auth. Enumerate/create users (< 1.4.1)',
    'vulhubPhpTitle': 'PHP 8.1.0-dev Backdoor / CVE-2012-1823 PHP-CGI RCE',
    'vulhubPhpCardTitle': 'PHP RCE Series',
    'vulhubPhpCardSubtitle': 'PHP 8.1.0-dev User-Agentt backdoor + CVE-2012-1823 PHP-CGI parameter injection',
    'vulhubSpringTitle': 'Spring Framework CVE-2022-22965/22963/CVE-2018-1273/CVE-2017-8046 RCE',
    'vulhubSpringCardTitle': 'Spring Framework RCE',
    'vulhubSpringCardSubtitle': 'Spring4Shell / Spring Cloud Function / Spring Data SpEL injection series',
    'vulhubStruts2Title': 'Apache Struts2 S2-032/045/053/057/059 RCE',
    'vulhubStruts2CardTitle': 'Apache Struts2 RCE',
    'vulhubStruts2CardSubtitle': 'S2-032 / S2-045 / S2-053 / S2-057 / S2-059 — OGNL expression injection',
    'vulhubTomcatTitle': 'Apache Tomcat CVE-2017-12615 PUT Method Arbitrary File Upload RCE',
    'vulhubTomcatCardTitle': 'Apache Tomcat CVE-2017-12615',
    'vulhubTomcatCardSubtitle': 'Upload JSP Webshell when PUT method is enabled (Tomcat 8.5.19)',
    'vulhubWeblogicTitle': 'Oracle WebLogic CVE-2019-2725/CVE-2020-14882/CVE-2020-14883 RCE',
    'vulhubWeblogicCardTitle': 'Oracle WebLogic RCE',
    'vulhubWeblogicCardSubtitle': 'XMLDecoder deserialization + console unauthenticated RCE',
    'vulhubXxljobTitle': 'XXL-JOB Unauthenticated Executor RCE',
    'vulhubXxljobCardTitle': 'XXL-JOB Unauthenticated RCE',
    'vulhubXxljobCardSubtitle': 'Unauthenticated Executor interface. Submit arbitrary shell commands via GLUE_SHELL type (2.2.0)',
    'vulhubAria2BtnListTasks': 'List active tasks',
    'vulhubAria2SectionCron': 'Cron write RCE',
    'vulhubAria2FieldCronUrl': 'Attacker cron file URL',
    'sectionFullTerminal': 'Full terminal',
    'fieldBasicAuth': 'Basic Auth credentials',
    'sectionVulnDetect': 'Vuln detection',
    'sectionGroovyRce': 'Groovy RCE execution',
    'sectionPathTraversal': 'Path traversal file read',
    'fieldFilePath': 'File path',
    'sectionCgiRce': 'CGI RCE (requires mod_cgi enabled)',
    'btnReadFile': 'Read file',
    'fieldCoreName': 'Core name',
    'sectionCmdExecOob': 'Command execution (blind, verify via OOB)',
    'sectionCmdExecAutoUpload': 'Command execution (auto-upload + execute)',
    'sectionCmdExecOobNeeded': 'Command execution (no output, OOB required)',
    'sectionCmdExecUserAgentInject': 'Command execution (via User-Agent injection)',
    'btnInjectAndTrigger': 'Inject and trigger',
    'sectionCveSelect': 'CVE selection',
    'fieldUsername': 'Username',
    'fieldPassword': 'Password',
    'nacosStep1': 'Step 1 — Create / use admin account',
    'nacosStep3': 'Step 3 — Cron reverse shell',
    'nacosListUsers': 'Enumerate users',
    'nacosCreateUser': 'Create user',
    'nacosLoginForToken': 'Login to get Token',
    'nacosTokenHint': 'Auto-filled after login',
    'nacosDerbySql': 'Arbitrary Derby SQL',
    'nacosExecSql': 'Execute SQL',
    'flaskSstiInjectParam': 'Injection parameter (GET)',
    'sectionRequestHeaders': 'Request headers',
    'fieldCustomHeaders': 'Custom headers',
    'sectionRequestBody': 'Request body',
    'flaskSstiBodyInject': 'Request body ({{INJECT}} is the injection point)',
    'flaskSstiBodyPostOnly': 'Request body (POST mode only)',
    'flaskSstiBtnDetect': 'Detect SSTI',
    'phpFieldFilePath': 'PHP file path',
    'struts2FieldPath': 'Path (005/007/052/053/057)',
    'supervisorBtnDetect': 'Detect XML-RPC',
    'xxljobBtnDetect': 'Detect unauthorized access',
    'ofbizBtnDetect51467': 'Detect CVE-2023-51467 (OFBiz 18.12.10)',
    'ofbizBtnDetect38856': 'Detect CVE-2024-38856 (OFBiz 18.12.11)',
    'tomcatFieldPath': 'Upload path',
    'expTagGeneric': 'Generic',
    'expTagZentao': 'Zentao',
    'expSubtitleShiro': 'rememberMe key bruteforce / Payload injection',
    'expVersionShiro': 'Shiro: <=1.2.4 | Condition: default rememberMe key',
    'expSubtitleThinkphp': '3.x/5.x/6.x vuln detection, RCE, GetShell',
    'expVersionThinkphp': 'ThinkPHP: 2.x / <=5.0.23 / 5.0.22/5.1.29 | Condition: route/gadget chain reachable',
    'expSubtitleZentao': 'Login bypass · Write Behinder WebShell via Repo config',
    'expVersionZentao': 'Zentao: see official advisory range | Condition: exploit path reachable',
    'expSubtitleStruts2': 'OGNL expression injection RCE series',
    'expVersionStruts2': 'Struts2: S2-032=2.3.20-2.3.28(except 2.3.20.3/2.3.24.3); S2-045/053/057/059=2.0.0-2.5.20 | Condition: matching OGNL trigger surface present',
    'expSubtitleSpring': 'Spring4Shell / Cloud Function / Data SpEL injection series',
    'expVersionSpring': 'Spring: 22965=5.3.17; 22963=SCF 3.2.2; 1273=Data Commons<=2.0.5; 8046=Data REST 2.6.6 | Condition: deployment matches each CVE',
    'expSubtitleHttpd': 'Path normalization flaw — path traversal + CGI RCE',
    'expVersionHttpd': 'HTTPd: =2.4.49 | Condition: directory config allows traversal',
    'expSubtitleDruid': 'Embedded JavaScript code injection RCE (≤ 0.20.0)',
    'expVersionDruid': 'Druid: <=0.20.0 | Condition: sampler/indexer endpoints reachable',
    'expSubtitleOfbiz': 'Unauthenticated Groovy code injection RCE',
    'expVersionOfbiz': 'OFBiz: 18.12.10 / 18.12.11 | Condition: ProgramExport path reachable',
    'expSubtitleSolr': 'RunExecutableListener arbitrary command execution (< 7.1.0)',
    'expVersionSolr': 'Solr: <7.1.0 | Condition: config API can write listener',
    'expSubtitleDrupal': 'Form API #post_render callback PHP execution',
    'expVersionDrupal': 'Drupal: <7.58; 8.x<8.3.9/<8.4.6/<8.5.1 | Condition: Form API path reachable',
    'expSubtitleElastic': 'Groovy script sandbox escape RCE (< 1.3.8 / < 1.4.3)',
    'expVersionElastic': 'Elasticsearch: <1.3.8 or <1.4.3 | Condition: dynamic scripting enabled',
    'expSubtitleFlaskSsti': 'Server-side template injection executes arbitrary Python code',
    'expVersionFlaskSsti': 'Flask/Jinja2: depends on components | Condition: SSTI injection point exists',
    'expTitlePhp': 'PHP 8.1.0-dev backdoor / CVE-2012-1823 PHP-CGI',
    'expSubtitlePhp': 'User-Agentt backdoor + CGI argument injection RCE',
    'expVersionPhp': 'PHP: 8.1.0-dev or CGI<5.3.12/<5.4.2 | Condition: backdoor header / CGI args reachable',
    'expSubtitleTomcat': 'Upload JSP Webshell when PUT method is enabled',
    'expVersionTomcat': 'Tomcat: 8.5.19 | Condition: DefaultServlet readonly=false',
    'expSubtitleWeblogic': 'XMLDecoder deserialization + console unauth + WS test page upload RCE',
    'expVersionWeblogic': 'WebLogic: 10271<10.3.6; 14882/14883=12.2.1.3(12.2.1+) | Condition: console/component reachable',
    'expTitleXxljob': 'XXL-JOB unauthenticated executor RCE',
    'expSubtitleXxljob': 'Submit arbitrary shell commands via GLUE_SHELL type (2.2.0)',
    'expVersionXxljob': 'XXL-JOB: cross-check official advisory | Condition: unauthenticated executor',
    'expSubtitleNacos': 'User-Agent auth bypass, enumerate/create users (< 1.4.1)',
    'expVersionNacos': 'Nacos: <1.4.1 | Condition: User-Agent bypass chain reachable',
    'menuEnterSuo5': 'Open suo5 Proxy',
    'menuEnterSuoTunnel': 'Open suo5',
    'titleSuo5Manager': 'suo5 Proxy',
    'suo5ManagementTitle': 'suo5 · {projectName}',
    'actionAddSuo5': 'Add suo5 Proxy',
    'suo5NewConfigTitle': 'New suo5 Proxy',
    'suo5EditConfigTitle': 'Edit suo5 Proxy',
    'suo5ConfigName': 'Profile name',
    'suo5ConfigNameHint': 'A friendly name',
    'suo5TargetUrl': 'suo5 URL',
    'suo5TargetUrlHint': 'https://target/path/suo5.php',
    'suo5ListenHost': 'Listen host',
    'suo5ListenPort': 'Listen port',
    'suo5Count': '{n} total',
    'suo5EmptyHint': 'No suo5 proxy yet. Click "{addLabel}" to get started',
    'confirmDeleteSuo5': 'Delete "{name}"? This action cannot be undone.',
    'suo5StatusRunning': 'Running',
    'suo5StatusConnecting': 'Connecting',
    'suo5StatusError': 'Error',
    'suo5StatusIdle': 'Idle',
    'suo5InvalidUrl': 'URL must be http/https',
    'suo5InvalidPort': 'Listen port is invalid',
    'suo5MissingUrl': 'Please enter the suo5 URL',
    'suo5RunningNoEdit': 'Cannot edit while running',
    'suo5StatActiveConn': 'Conns',
    'suo5StatUpload': 'Upload',
    'suo5StatDownload': 'Download',
    'suo5RunLog': 'Run log',
    'suo5NoLogs': '> No logs yet',
    'suo5LogCopiedSnack': 'Logs copied',
    'suo5HandshakeOk': 'Handshake OK',
    'suo5HandshakeFailed': 'Handshake failed: {e}',
    'suo5BtnProbe': 'Probe',
    'suoProbeHandshakeLoading': 'Testing handshake with server…',
    'suoHandshakeResultTitle': 'Handshake result',
    'suo5MappingLabel': 'Local listen',
    'suo5ActiveBanner': '{statusLabel} · {name}',
    'suo5HeaderRunningSummary': 'Running {running} / {total}',
    'menuSuoTunnel': 'suo5/suo6',
    'menuMcp': 'MCP',
    'titleSuoTunnelManager': 'suo5/suo6',
    'suoTunnelManagementTitle': 'suo5/suo6 · {projectName}',
    'actionAddSuoTunnel': 'Add proxy',
    'tooltipWebshellOneClickTunnel': 'Create suo tunnel',
    'webshellJspSuoTunnelPickTitle': 'Choose tunnel protocol',
    'webshellJspSuoTunnelPickBody': 'Pick suo5 or suo6 for JSP. With Behinder, memory injection is tried first; on failure, the jsp file is uploaded if the shell is writable.',
    'webshellOneClickTunnelUnavailable': 'Cannot create tunnel for this shell',
    'webshellOneClickTunnelNeedConn': 'Connect to the shell first',
    'webshellOneClickTunnelPayloadMissing': 'Tunnel script not in library (e.g. suo5.jsp / suo6.jsp). Sync defaults on the Payloads page',
    'webshellOneClickTunnelUploadFailed': 'Failed to upload tunnel script beside the webshell',
    'suoTunnelNewConfigTitle': 'New proxy',
    'suoTunnelEditConfigTitle': 'Edit proxy',
    'suoTunnelProtocol': 'Protocol',
    'suoTunnelProtocolSuo5': 'suo5',
    'suoTunnelProtocolSuo6': 'suo6',
    'suoTunnelRunLog': 'Run log',
    'suoTunnelEmptyHint': 'No profiles. Tap "{addLabel}" to add one.',
    'suoTunnelCount': '{n} total',
    'suoTunnelProfileCreatedSnack': 'Proxy profile saved',
    'suoTunnelProtocolSwitchTitle': 'Change protocol',
    'suoTunnelProtocolSwitchBody': 'This removes the current profile and creates a new one with the same URL and listen settings. Continue?',
    'confirmDeleteSuo6': 'Delete config "{name}"?',
    'suo6MissingUrl': 'Please enter the suo6 URL',
    'obfuscateUploadLabel': 'Obfuscate & compress on upload',
    'obfuscateUploadTooltip': 'Before upload: PHP gzip+eval obfuscation; JSP/ASP/ASPX one-line minify with random 6-char hex identifiers',
    'obfuscateModeOn': 'Obfuscate mode ON — next upload auto-obfuscates (PHP: compress; JSP/ASP/ASPX: one line + hex names)',
    'obfuscateModeOff': 'Obfuscate mode OFF',
    'tooltipDeobfuscate': 'Deobfuscate',
    'tooltipShowObfuscated': 'Show obfuscated source',
    'obfuscatedFileDialogTitle': 'Obfuscated file detected',
    'obfuscatedFileDialogMsg': 'This file contains obfuscated/compressed code. Save the deobfuscated version?',
    'btnSaveDeobfuscated': 'Save deobfuscated',
    'btnSaveAsIs': 'Save as-is',
    'tooltipDetectWritableDirs': 'Detect writable directories',
    'writableDirsDialogTitle': 'Writable Directories',
    'writableDirsNoneFound': 'No writable directories found',
    'writableDirsFoundHint': 'Found {n} writable directories. Tap to navigate:',
  };
}
